In [7]:
import pandas as pd
import json

In [187]:
def obtener_las_que_tienen_ref_a_factura_electronica(lista_referencias):
    if lista_referencias:
        for factura in lista_referencias:
            if factura['Tipo'] == '33':
                return True
        return False
    
    else:
        return False

In [188]:
def obtener_la_referencia(lista_referencias):
    if lista_referencias:
        for factura in lista_referencias:
            if factura['Tipo'] == '33':
                return factura['Folio']

In [159]:
df = pd.read_excel('input\\reporte_97131163.xls')

In [197]:
df_2 = df.copy()
df_2['tipo'] = df_2['tipo'].astype(str)
df_2['referencias'] = df_2['referencias'].apply( \
                    lambda x: json.loads(x, strict = False) if type(x) == str else None)
df_sin_nc_ni_gd = df_2.query('not(tipo == "61" or tipo == "52")')

In [198]:
mask_tienen_referencia_fe = df_sin_nc_ni_gd['referencias'].apply(obtener_las_que_tienen_ref_a_factura_electronica)
df_posibles_refacturaciones = df_sin_nc_ni_gd[mask_tienen_referencia_fe]
df_posibles_refacturaciones.head(5)

,tipo,tipo_documento,folio,emisor,razon_social_emisor,receptor,publicacion,emision,monto_neto,monto_exento,...,fecha_ingreso_oc,folio_rc,fecha_ingreso_rc,ticket_devengo,folio_sigfe,tarea_actual,area_transaccional,fecha_ingreso,fecha_aceptacion,fecha
500,33,factura_electronica,22956,77.006.073-7,DFM PHARMA SPA,61.608.402-K,2022-10-04 00:06:00,2022-10-03,99500,0,...,2022-03-22 16:03:16,NaN,NaN,NaN,NaN,DevengoManual,1642002,2022-10-04 00:06,2022-10-03 08:45,NaN
501,33,factura_electronica,22965,77.006.073-7,DFM PHARMA SPA,61.608.402-K,2022-10-04 00:06:00,2022-10-03,5400,0,...,2021-09-01 12:09:52,NaN,NaN,NaN,NaN,DevengoManual,1642002,2022-10-04 00:06,2022-10-03 08:45,NaN
502,33,factura_electronica,22995,77.006.073-7,DFM PHARMA SPA,61.608.402-K,2022-10-04 00:09:00,2022-10-03,413100,0,...,2022-01-21 11:01:04,NaN,NaN,NaN,NaN,DevengoManual,1642002,2022-10-04 00:09,2022-10-03 08:50,NaN
503,33,factura_electronica,22991,77.006.073-7,DFM PHARMA SPA,61.608.402-K,2022-10-04 00:09:00,2022-10-03,675000,0,...,2022-03-22 16:03:28,NaN,NaN,NaN,NaN,DevengoManual,1642002,2022-10-04 00:09,2022-10-03 08:50,NaN
504,33,factura_electronica,23002,77.006.073-7,DFM PHARMA SPA,61.608.402-K,2022-10-04 00:09:00,2022-10-03,42300,0,...,2021-08-02 15:08:31,NaN,NaN,NaN,NaN,DevengoManual,1642002,2022-10-04 00:09,2022-10-03 08:50,NaN

In [201]:
df_posibles_refacturaciones['referencia_refacturacion'] = df_posibles_refacturaciones['referencias'].apply(obtener_la_referencia)
df_posibles_refacturaciones['llave_id_ref'] = df_posibles_refacturaciones['emisor'] + df_posibles_refacturaciones['referencia_refacturacion']

C:\Users\gmolina\AppData\Local\Temp\ipykernel_11328\2303591185.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_posibles_refacturaciones['referencia_refacturacion'] = df_posibles_refacturaciones['referencias'].apply(obtener_la_referencia)
C:\Users\gmolina\AppData\Local\Temp\ipykernel_11328\2303591185.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_posibles_refacturaciones['llave_id_ref'] = df_posibles_refacturaciones['emisor'] + df_posibles_refacturaciones['referencia_refacturacion']

In [203]:
df_posibles_refacturaciones

33         49
214431      3
43983       2
44005       2
43986       2
44004       2
210852      1
682389      1
682252      1
214553      1
214229      1
214477      1
682527      1
210209      1
210590      1
640099      1
210845      1
640146      1
24033       1
624516      1
640147      1
640018      1
18423       1
113147      1
624914      1
202885      1
202858      1
202821      1
526036      1
7505        1
192636      1
192635      1
233566      1
682598      1
1757940     1
62987       1
62718       1
674484      1
674485      1
674497      1
674490      1
202866      1
202875      1
674496      1
39686       1
209608      1
Name: referencia_refacturacion, dtype: int64